# Generated by Django 5.1.7 on 2025-05-26 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_enseignements', '0002_initial'),
        ('_inscriptions', '0001_initial'),
        ('_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_users.apprenant'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_enseignements.filiere'),
        ),
        migrations.AddField(
            model_name='documentcandidature',
            name='candidature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_inscriptions.candidature'),
        ),
        migrations.AddField(
            model_name='typedocument',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_enseignements.filiere'),
        ),
        migrations.AddField(
            model_name='documentcandidature',
            name='type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_inscriptions.typedocument'),
        ),
    ]
