# Generated by Django 5.1.7 on 2025-05-26 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_enseignements', '0002_initial'),
        ('_paiements', '0001_initial'),
        ('_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_users.apprenant'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_enseignements.filiere'),
        ),
        migrations.AddField(
            model_name='tranchepaiement',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='_enseignements.filiere'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='tranche_actuelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_paiements.tranchepaiement'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='_paiements.paiement'),
        ),
    ]
