# Generated by Django 5.1.7 on 2025-05-26 18:08

import _enseignements.validators
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la classe')),
                ('annee_scolaire', models.CharField(help_text='Format: 2023-2024', max_length=9, verbose_name='Année scolaire')),
                ('effectif', models.PositiveIntegerField(default=0, verbose_name='Effectif')),
                ('status', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['annee_scolaire', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du département')),
                ('sigle', models.CharField(max_length=50, verbose_name='Sigle')),
                ('status', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'établissement")),
                ('sigle', models.CharField(help_text='Ex: UJKZ', max_length=10, verbose_name='Sigle')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('site', models.URLField(blank=True, max_length=100, null=True, verbose_name='Site web')),
                ('logo', models.FileField(default='default_logo.png', upload_to='etablissements/logos/', validators=[_enseignements.validators.validate_file_extension_for_image], verbose_name='Logo')),
                ('directeur_general', models.CharField(help_text='Nom complet du directeur', max_length=50, verbose_name='Directeur général')),
                ('status', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la filière')),
                ('sigle', models.CharField(max_length=50, verbose_name='Sigle')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frais de formation')),
                ('status', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la localité')),
                ('status', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Localité',
                'verbose_name_plural': 'Localités',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, verbose_name='Code matière')),
                ('intitule', models.CharField(max_length=100, verbose_name='Intitulé')),
                ('objectif', models.TextField(verbose_name='Objectifs pédagogiques')),
                ('duree', models.PositiveIntegerField(help_text='Durée totale en heures', verbose_name='Durée totale (heures)')),
                ('temps_cours_magistral', models.PositiveIntegerField(default=0, verbose_name='Heures de cours magistral')),
                ('temps_travaux_dirige', models.PositiveIntegerField(default=0, verbose_name='Heures de travaux dirigés')),
                ('temps_travaux_pratique', models.PositiveIntegerField(default=0, verbose_name='Heures de travaux pratiques')),
                ('credit', models.PositiveIntegerField(default=0, verbose_name='Crédits ECTS')),
                ('status', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code du module')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom du module')),
                ('objectif_general', tinymce.models.HTMLField(verbose_name='Objectif général')),
                ('objectif_specifique', tinymce.models.HTMLField(verbose_name='Objectif spécifique')),
                ('status', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': "Module d'enseignement",
                'verbose_name_plural': "Modules d'enseignement",
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ex: BTS, Licence, Master, Doctorat', max_length=50, verbose_name='Nom du niveau')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='Pour le tri des niveaux', verbose_name="Ordre d'affichage")),
                ('status', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Niveau académique',
                'verbose_name_plural': 'Niveaux académiques',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='RessourcePdf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fichier', models.FileField(upload_to='ressources/pdfs/%Y/%m/%d/', validators=[_enseignements.validators.validate_file_extension_for_image], verbose_name='Fichier PDF')),
                ('date_publication', models.DateField(auto_now_add=True, verbose_name='Date de publication')),
                ('status', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Ressource PDF',
                'verbose_name_plural': 'Ressources PDF',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='RessourceVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(verbose_name='URL de la vidéo')),
                ('date_publication', models.DateField(auto_now_add=True, verbose_name='Date de publication')),
                ('status', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Ressource vidéo',
                'verbose_name_plural': 'Ressources vidéo',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ex: Semestre 1, Semestre 2', max_length=50, verbose_name='Nom du semestre')),
                ('code', models.CharField(help_text='Code court (ex: S1)', max_length=10, unique=True, verbose_name='Code')),
                ('status', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Semestre académique',
                'verbose_name_plural': 'Semestres académiques',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la spécialité')),
                ('status', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='StatutEtablissement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ex: Public, Privé, Confessionnel', max_length=100, unique=True, verbose_name='Statut')),
                ('status', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': "Statut d'établissement",
                'verbose_name_plural': "Statuts d'établissements",
            },
        ),
        migrations.CreateModel(
            name='TypeEtablissement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ex: Université, Grande École, Institut', max_length=100, unique=True, verbose_name="Type d'établissement")),
                ('status', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': "Type d'établissement",
                'verbose_name_plural': "Types d'établissements",
            },
        ),
    ]
