# Generated by Django 5.1.7 on 2025-06-02 13:17

import _enseignements.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_enseignements', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['code'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.RemoveConstraint(
            model_name='module',
            name='unique_module_specialite',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='chef',
        ),
        migrations.RemoveField(
            model_name='module',
            name='objectif_general',
        ),
        migrations.RemoveField(
            model_name='module',
            name='objectif_specifique',
        ),
        migrations.RemoveField(
            model_name='module',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='module',
            name='specialite',
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='module',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='_enseignements.filiere', verbose_name='Filière concernée'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='_enseignements.etablissement', verbose_name='Établissement de rattachement'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='etablissement/logo/', validators=[_enseignements.validators.validate_file_extension_for_image], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='module',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='_enseignements.niveau', verbose_name='Niveau académique'),
        ),
        migrations.AlterField(
            model_name='module',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom du module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='_enseignements.semestre', verbose_name='Semestre'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('nom', 'filiere', 'niveau', 'semestre'), name='unique_module_in_context'),
        ),
    ]
