# Generated by Django 5.1.7 on 2025-06-02 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_enseignements', '0003_alter_module_options_and_more'),
        ('_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefdepartement',
            name='departement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_attribue', to='_enseignements.departement', verbose_name='Département dirigé'),
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprenants', to='_enseignements.departement', verbose_name="Département d'affiliation"),
        ),
        migrations.RemoveField(
            model_name='chefdepartement',
            name='date_nomination',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='departements',
            field=models.ManyToManyField(blank=True, related_name='enseignants', to='_enseignements.departement', verbose_name='Départements où enseigne'),
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
    ]
