# Generated by Django 5.1.7 on 2025-06-02 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_users', '0002_alter_chefdepartement_departement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='profile_content_type',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='profile_object_id',
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_apprenant', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur associé'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_enseignant', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur associé'),
        ),
    ]
