# Generated by Django 5.1.7 on 2025-06-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_users', '0003_remove_utilisateur_profile_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_name',
        ),
    ]
