databases:
  - name: formis-db
    plan: free

services:
  - type: web
    name: formis-api
    env: python
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    startCommand: gunicorn formis_api.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: formis_api.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: formis-api.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: formis-db
          property: connectionString
